### ISSUE TITLE
Output directory for the generated PDF

### ISSUE THREAD

**Issue by UweZiegenhagen** [dante-ev/latex-action#12]
Hi there, 

I tried it today (https://github.com/UweZiegenhagen/GH_TL_Action_Test) and can't find the generated PDF.  Do I need to specify a subfolder as output directory?

**Comment by UweZiegenhagen** [comment]
I tried the following, no success

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: Main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Main.pdf

**Comment by mbg** [comment]
I am not the author of this action, but your question is not specific to this - build artifacts can be found in the actions tab for each build, e.g. your most recent run: https://github.com/UweZiegenhagen/GH_TL_Action_Test/actions/runs/695060889 has an "Artifacts" section at the bottom from where you can download the PDF.

**Comment by koppor** [comment]
Note that the "artifacts" are deleted after some time. One has to re-run the job if one wants to download the artifact.

Current example, where an artifact exists: https://github.com/dante-ev/docker-texlive/pull/40/checks

![grafik](https://user-images.githubusercontent.com/1366654/121606625-ccf80c00-ca4e-11eb-8976-a01ba6448f2b.png)

![grafik](https://user-images.githubusercontent.com/1366654/121606643-d3868380-ca4e-11eb-9610-50cb0a1b77ed.png)

![grafik](https://user-images.githubusercontent.com/1366654/121606689-e8631700-ca4e-11eb-8546-2dcc6003b95d.png)

**Comment by usersina** [comment]
Here! This will build the `main.tex` file and create a `main.pdf` in a zip.

```yaml
name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
          # args: -output-directory=out -aux-directory=out => Gives a bunch of errors

      - name: Print folder structure
        run: tree

      - name: Upload main.pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: main.pdf
```
