### ISSUE TITLE
Subfiles functionality seems to struggle with permissions

### ISSUE THREAD

**Issue by bredamatt** [dante-ev/latex-action#21]
Hi,

I just tested this. It has been about 4-5 years since I've used LaTeX last, and today was the first time I picked it back up. 

I have created a very simple directory structure:

```
.
├── README.md
├── out
└── src
    ├── chapters
    │   ├── chapter1.tex
    │   ├── chapter2.tex
    │   └── chapter3.tex
    └── main.tex
```

Locally, I can do the following from the root:

```
$ pdflatex --output-dir out/ src/main.tex
```

which then adds the following to the `out/` dir:

```
out
├── main.aux
├── main.log
└── main.pdf
```

I am trying to do exactly the same with my action as follows:

```
- name: pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -output-dir=out -no-shell-escape
```

However, I get this error:

```
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021) (preloaded format=pdflatex)
entering extended mode
! I can't write on file `main.log'.
(Press Enter to retry, or Control-D to exit; default file extension is `.log')
Please type another transcript file name: 
! Emergency stop
!  ==> Fatal error occurred, no output PDF file produced!
```

This seems like the runner has a permission issue tgo write on the `main.log` file. 

Note  that before I added subfiles to the project, I did not have this issue.
