### ISSUE TITLE
makeglossaries?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [dante-ev/latex-action#22]
Hi @koppor 

Any idea how to use the makeglossaries option? 

This is a screenshot from the Kaobook documentation.

![image](https://user-images.githubusercontent.com/40028739/175068128-8ee3b839-31b2-460e-abc8-1c65dc11ab79.png)

**Comment by RemDelaporteMathurin** [comment]
I find a way to do it, but I wanted to check with you if there was a better option:

```yml
name: Build LaTeX document

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
          
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        run: |
          latexmk -pdf main.tex
          makeglossaries main
          latexmk -pdf main.tex
```
