### ISSUE TITLE
Labels ref is rendered as `??`

### ISSUE THREAD

**Issue by jmeinlschmidt** [dante-ev/latex-action#24]
While the `\ref` macro renders normally in Overleaf, I get `??` for all references in the resulting file when processing this action.

Examples:
```latex
\ref{analysis}

% ...

\section{Analysis and design}
\label{analysis}
```

Used configuration
```yaml
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: $TEXT_SRC.tex
          compiler: lualatex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -shell-escape
```

Any ideas? Thank you!
